export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const VERIFY_TOKEN_REQ = "VERIFY_TOKEN_REQ";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED";

export const FORGOT_PASSWORD_REQ = "FORGOT_PASSWORD_REQ";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const CHANGE_PASSWORD_REQ = "CHANGE_PASSWORD_REQ";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_SELECTED_TAB = "SET_SELECTED_TAB";

export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const NAVIGATE = "NAVIGATE";
export const GOBACK = "GOBACK";
export const SET_NAVIGATION_REF = "SET_NAVIGATION_REF";
export const NAV_DISPATCH = "NAV_DISPATCH";
export const REPLACE = "REPLACE";

export const SET_TOAST_REF = "SET_TOAST_REF";
export const NOTIFY = "NOTIFY";

export const SIGNUP_VERIFY_REQ = "SIGNUP_VERIFY_REQ";
export const SIGNUP_VERIFY_SUCCESS = "SIGNUP_VERIFY_SUCCESS";
export const SIGNUP_VERIFY_FAILED = "SIGNUP_VERIFY_FAILED";

export const RESEND_OTP_REQ = "RESEND_OTP_REQ";
export const RESEND_OTP_SUC = "RESEND_OTP_SUC";
export const RESEND_OTP_FAILED = "RESEND_OTP_FAILED";

export const FETCH_ALL_RESTAURANTS_REQ = "FETCH_ALL_RESTAURANTS_REQ";
export const FETCH_ALL_RESTAURANTS_SUC = "FETCH_ALL_RESTAURANTS_SUC";
export const FETCH_ALL_RESTAURANTS_FAILED = "FETCH_ALL_RESTAURANTS_FAILED";

export const ADD_RESTAURANT_TO_FAVOURITE_REQ =
  "ADD_RESTAURANT_TO_FAVOURITE_REQ";
export const ADD_RESTAURANT_TO_FAVOURITE_SUC =
  "ADD_RESTAURANT_TO_FAVOURITE_SUC";
export const ADD_RESTAURANT_TO_FAVOURITE_FAILED =
  "ADD_RESTAURANT_TO_FAVOURITE_FAILED";

export const REMOVE_RESTAURANT_FROM_FAVOURITE_REQ =
  "REMOVE_RESTAURANT_FROM_FAVOURITE_REQ";
export const REMOVE_RESTAURANT_FROM_FAVOURITE_SUC =
  "REMOVE_RESTAURANT_FROM_FAVOURITE_SUC";
export const REMOVE_RESTAURANT_FROM_FAVOURITE_FAILED =
  "REMOVE_RESTAURANT_FROM_FAVOURITE_FAILED";

export const FETCH_FAVOURITE_RESTAURANTS_REQ =
  "FETCH_FAVOURITE_RESTAURANTS_REQ";
export const FETCH_FAVOURITE_RESTAURANTS_SUC =
  "FETCH_FAVOURITE_RESTAURANTS_SUC";
export const FETCH_FAVOURITE_RESTAURANTS_FAILED =
  "FETCH_FAVOURITE_RESTAURANTS_FAILED";

export const FETCH_IS_FAVOURITE_RESTAURANTS_REQ =
  "FETCH_IS_FAVOURITE_RESTAURANTS_REQ";
export const FETCH_IS_FAVOURITE_RESTAURANTS_SUC =
  "FETCH_IS_FAVOURITE_RESTAURANTS_SUC";
export const FETCH_IS_FAVOURITE_RESTAURANTS_FAILED =
  "FETCH_IS_FAVOURITE_RESTAURANTS_FAILED";

export const FETCH_RESTAURANT_BY_SEARCH_REQ = "FETCH_RESTAURANT_BY_SEARCH_REQ";
export const FETCH_RESTAURANT_BY_SEARCH_SUCCESS =
  "FETCH_RESTAURANT_BY_SEARCH_SUCCESS";
export const FETCH_RESTAURANT_BY_SEARCH_FAILED =
  "FETCH_RESTAURANT_BY_SEARCH_FAILED";

export const FETCH_RESTAURANTS_CATEGORY_REQ = "FETCH_RESTAURANTS_CATEGORY_REQ";
export const FETCH_RESTAURANTS_CATEGORY_SUC = "FETCH_RESTAURANTS_CATEGORY_SUC";
export const FETCH_RESTAURANTS_CATEGORY_FAILED =
  "FETCH_RESTAURANTS_CATEGORY_FAILED";

export const FETCH_RESTAURANT_BY_CATEGORY_REQ =
  "FETCH_RESTAURANT_BY_CATEGORY_REQ";
export const FETCH_RESTAURANT_BY_CATEGORY_SUC =
  "FETCH_RESTAURANT_BY_CATEGORY_SUC";
export const FETCH_RESTAURANT_BY_CATEGORY_FAILED =
  "FETCH_RESTAURANT_BY_CATEGORY_FAILED";

export const FETCH_RESTAURANT_BY_ID_REQ = "FETCH_RESTAURANT_BY_ID_REQ";
export const FETCH_RESTAURANT_BY_ID_SUCCESS = "FETCH_RESTAURANT_BY_ID_SUCCESS";
export const FETCH_RESTAURANT_BY_ID_FAILED = "FETCH_RESTAURANT_BY_ID_FAILED";

export const FETCH_SIMILAR_RESTAURANT_BY_ID_REQ =
  "FETCH_RESTAURANT_SIMILAR_BY_ID_REQ";
export const FETCH_SIMILAR_RESTAURANT_BY_ID_SUCCESS =
  "FETCH_RESTAURANT_SIMILAR_BY_ID_SUCCESS";
export const FETCH_SIMILAR_RESTAURANT_BY_ID_FAILED =
  "FETCH_RESTAURANT_SIMILAR_BY_ID_FAILED";

export const FETCH_SIMILAR_PERCENT_RESTAURANT_BY_ID_REQ =
  "FETCH_RESTAURANT_PERCENT_SIMILAR_BY_ID_REQ";
export const FETCH_SIMILAR_PERCENT_RESTAURANT_BY_ID_SUCCESS =
  "FETCH_RESTAURANT_PERCENT_SIMILAR_BY_ID_SUCCESS";
export const FETCH_SIMILAR_PERCENT_RESTAURANT_BY_ID_FAILED =
  "FETCH_RESTAURANT_PERCENT_SIMILAR_BY_ID_FAILED";

export const FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_REQ =
  "FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_REQ";
export const FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_SUCCESS =
  "FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_SUCCESS";
export const FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_FAILED =
  "FETCH_RESTAURANT_MENUS_BY_RESTAURANT_ID_FAILED";

export const FETCH_TABLE_BY_RESTAURANT_REQ = "FETCH_TABLE_BY_RESTAURANT_REQ";
export const FETCH_TABLE_BY_RESTAURANT_SUC = "FETCH_TABLE_BY_RESTAURANT_SUC";
export const FETCH_TABLE_BY_RESTAURANT_FAILED =
  "FETCH_TABLE_BY_RESTAURANT_FAILED";

export const CONFIRM_TABLE_BOOKIN_REQ = "CONFIRM_TABLE_BOOKIN_REQ";
export const CONFIRM_TABLE_BOOKIN_SUC = "CONFIRM_TABLE_BOOKIN_SUC";
export const CONFIRM_TABLE_BOOKIN_FAILED = "CONFIRM_TABLE_BOOKIN_FAILED";

export const FETCH_MY_RESERVATION_REQ = "FETCH_MY_RESERVATION_REQ";
export const FETCH_MY_RESERVATION_SUC = "FETCH_MY_RESERVATION_SUC";
export const FETCH_MY_RESERVATION_FAILED = "FETCH_MY_RESERVATION_FAILED";

export const CANCEL_RESERVATION_REQ = "CANCEL_RESERVATION_REQ";
export const CANCEL_RESERVATION_SUC = "CANCEL_RESERVATION_SUC";
export const CANCEL_RESERVATION_FAILED = "CANCEL_RESERVATION_FAILED";

export const NAVIGATE_WITH_PROPS = "NAVIGATE_WITH_PROPS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CLEAR_RESTAURANT_BY_ID = "CLEAR_RESTAURANT_BY_ID";
export const CLEAR_BOOKING_STATUS = "CLEAR_BOOKING_STATUS";

export const FETCH_TAGS_REQ = "FETCH_TAGS_REQ";
export const FETCH_TAGS_SUC = "FETCH_TAGS_SUC";
export const FETCH_TAGS_FAILED = "FETCH_TAGS_FAILED";

export const SAVE_USER_TAGS_REQ = "SAVE_USER_TAGS_REQ";
export const SAVE_USER_TAGS_SUC = "SAVE_USER_TAGS_SUC";
export const SAVE_USER_TAGS_FAILED = "SAVE_USER_TAGS_FAILED";
