export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const VERIFY_TOKEN_REQ = "VERIFY_TOKEN_REQ";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED";

export const FORGOT_PASSWORD_REQ = "FORGOT_PASSWORD_REQ";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const CHANGE_PASSWORD_REQ = "CHANGE_PASSWORD_REQ";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_SELECTED_TAB = "SET_SELECTED_TAB";

export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const NAVIGATE = "NAVIGATE";
export const GOBACK = "GOBACK";
export const SET_NAVIGATION_REF = "SET_NAVIGATION_REF";
export const REPLACE = "REPLACE";

export const SET_TOAST_REF = "SET_TOAST_REF";
export const NOTIFY = "NOTIFY";

export const SIGNUP_VERIFY_REQ = "SIGNUP_VERIFY_REQ";
export const SIGNUP_VERIFY_SUCCESS = "SIGNUP_VERIFY_SUCCESS";
export const SIGNUP_VERIFY_FAILED = "SIGNUP_VERIFY_FAILED";

export const RESEND_OTP_REQ = "RESEND_OTP_REQ";
export const RESEND_OTP_SUC = "RESEND_OTP_SUC";
export const RESEND_OTP_FAILED = "RESEND_OTP_FAILED";

export const FETCH_ALL_RESTAURANTS_REQ = "FETCH_ALL_RESTAURANTS_REQ";
export const FETCH_ALL_RESTAURANTS_SUC = "FETCH_ALL_RESTAURANTS_SUC";
export const FETCH_ALL_RESTAURANTS_FAILED = "FETCH_ALL_RESTAURANTS_FAILED";

export const FETCH_RESTAURANTS_CATEGORY_REQ = "FETCH_RESTAURANTS_CATEGORY_REQ";
export const FETCH_RESTAURANTS_CATEGORY_SUC = "FETCH_RESTAURANTS_CATEGORY_SUC";
export const FETCH_RESTAURANTS_CATEGORY_FAILED =
  "FETCH_RESTAURANTS_CATEGORY_FAILED";

export const FETCH_RESTAURANT_BY_CATEGORY_REQ =
  "FETCH_RESTAURANT_BY_CATEGORY_REQ";
export const FETCH_RESTAURANT_BY_CATEGORY_SUC =
  "FETCH_RESTAURANT_BY_CATEGORY_SUC";
export const FETCH_RESTAURANT_BY_CATEGORY_FAILED =
  "FETCH_RESTAURANT_BY_CATEGORY_FAILED";

export const NAVIGATE_WITH_PROPS = "NAVIGATE_WITH_PROPS";
